# PhlexTargetUtils.cmake
#
# Shared utilities for discovering CMake targets, their types, and source files.
# Use in both CreateClangTidyTargets.cmake and CreateCoverageTargets.cmake.

include_guard()

# Recursively gather all build system targets starting from a source directory
function(phlex_gather_targets_recursive out_var directory)
  get_directory_property(_this_dir_targets DIRECTORY "${directory}" BUILDSYSTEM_TARGETS)
  if(_this_dir_targets)
    list(APPEND _collected ${_this_dir_targets})
  endif()
  get_directory_property(_subs DIRECTORY "${directory}" SUBDIRECTORIES)
  foreach(_sd IN LISTS _subs)
    phlex_gather_targets_recursive(_child "${_sd}")
    if(_child)
      list(APPEND _collected ${_child})
    endif()
  endforeach()
  if(_collected)
    list(REMOVE_DUPLICATES _collected)
  endif()
  set(${out_var} "${_collected}" PARENT_SCOPE)
endfunction()

# Collect all targets of a given type (EXECUTABLE, STATIC_LIBRARY,
# SHARED_LIBRARY, etc.)
function(phlex_collect_targets_by_type out_var type)
  phlex_gather_targets_recursive(_all_targets "${CMAKE_CURRENT_BINARY_DIR}")
  set(_filtered)
  foreach(_t IN LISTS _all_targets)
    get_target_property(_imported ${_t} IMPORTED)
    if(_imported)
      continue()
    endif()
    get_target_property(_t_type ${_t} TYPE)
    if(_t_type STREQUAL "${type}")
      list(APPEND _filtered ${_t})
    endif()
  endforeach()
  set(${out_var} "${_filtered}" PARENT_SCOPE)
endfunction()

# Collect absolute source files for a target
function(phlex_collect_target_sources out_var target)
  get_target_property(_t_src_dir ${target} SOURCE_DIR)
  get_target_property(_t_bin_dir ${target} BINARY_DIR)
  get_target_property(_sources ${target} SOURCES)
  set(_accum)
  foreach(_s IN LISTS _sources)
    if(NOT _s OR _s MATCHES [=[^$<]=])
      continue()
    endif()
    if(IS_ABSOLUTE "${_s}")
      set(_abs "${_s}")
    else()
      if(_t_src_dir)
        set(_cand "${_t_src_dir}/${_s}")
        if(EXISTS "${_cand}")
          get_filename_component(_abs "${_cand}" ABSOLUTE)
        endif()
      endif()
      if(NOT _abs AND _t_bin_dir)
        set(_cand2 "${_t_bin_dir}/${_s}")
        if(EXISTS "${_cand2}")
          get_filename_component(_abs "${_cand2}" ABSOLUTE)
        endif()
      endif()
      if(NOT _abs AND _t_src_dir)
        get_filename_component(_abs "${_s}" ABSOLUTE BASE_DIR "${_t_src_dir}")
      endif()
    endif()
    if(_abs)
      list(APPEND _accum "${_abs}")
    endif()
  endforeach()
  if(_accum)
    list(REMOVE_DUPLICATES _accum)
  endif()
  set(${out_var} "${_accum}" PARENT_SCOPE)
endfunction()
