# CMake generated Testfile for 
# Source directory: /workspace/test/max-parallelism
# Build directory: /workspace/build-debug/test/max-parallelism
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[job:check_parallelism_default]=] "/workspace/build-debug/_deps/cetmodules-src/libexec/cet_exec_test" "--wd" "/workspace/build-debug/test/max-parallelism/job:check_parallelism_default.d" "--remove-on-failure" "" "--required-files" "" "--datafiles" "" "--skip-return-code" "247" "/workspace/build-debug/bin/phlex" "-c" "/workspace/build-debug/test/max-parallelism/check_parallelism_default.jsonnet")
set_tests_properties([=[job:check_parallelism_default]=] PROPERTIES  ENVIRONMENT "SPDLOG_LEVEL=debug;PHLEX_PLUGIN_PATH=/workspace/build-debug" LABELS "DEFAULT;RELEASE" SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/workspace/build-debug/test/max-parallelism/job:check_parallelism_default.d" _BACKTRACE_TRIPLES "/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1186;add_test;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1143;_cet_add_test_detail;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;704;_cet_add_test;/workspace/test/max-parallelism/CMakeLists.txt;10;cet_test;/workspace/test/max-parallelism/CMakeLists.txt;0;")
add_test([=[job:check_parallelism_cli]=] "/workspace/build-debug/_deps/cetmodules-src/libexec/cet_exec_test" "--wd" "/workspace/build-debug/test/max-parallelism/job:check_parallelism_cli.d" "--remove-on-failure" "" "--required-files" "" "--datafiles" "" "--skip-return-code" "247" "/workspace/build-debug/bin/phlex" "-c" "/workspace/build-debug/test/max-parallelism/check_parallelism_cli.jsonnet" "-j" "7")
set_tests_properties([=[job:check_parallelism_cli]=] PROPERTIES  ENVIRONMENT "SPDLOG_LEVEL=debug;PHLEX_PLUGIN_PATH=/workspace/build-debug" LABELS "DEFAULT;RELEASE" SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/workspace/build-debug/test/max-parallelism/job:check_parallelism_cli.d" _BACKTRACE_TRIPLES "/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1186;add_test;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1143;_cet_add_test_detail;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;704;_cet_add_test;/workspace/test/max-parallelism/CMakeLists.txt;24;cet_test;/workspace/test/max-parallelism/CMakeLists.txt;0;")
add_test([=[job:check_parallelism_config]=] "/workspace/build-debug/_deps/cetmodules-src/libexec/cet_exec_test" "--wd" "/workspace/build-debug/test/max-parallelism/job:check_parallelism_config.d" "--remove-on-failure" "" "--required-files" "" "--datafiles" "" "--skip-return-code" "247" "/workspace/build-debug/bin/phlex" "-c" "/workspace/build-debug/test/max-parallelism/check_parallelism_config.jsonnet")
set_tests_properties([=[job:check_parallelism_config]=] PROPERTIES  ENVIRONMENT "SPDLOG_LEVEL=debug;PHLEX_PLUGIN_PATH=/workspace/build-debug" LABELS "DEFAULT;RELEASE" SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/workspace/build-debug/test/max-parallelism/job:check_parallelism_config.d" _BACKTRACE_TRIPLES "/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1186;add_test;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1143;_cet_add_test_detail;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;704;_cet_add_test;/workspace/test/max-parallelism/CMakeLists.txt;40;cet_test;/workspace/test/max-parallelism/CMakeLists.txt;0;")
add_test([=[job:check_parallelism_cli_over_config]=] "/workspace/build-debug/_deps/cetmodules-src/libexec/cet_exec_test" "--wd" "/workspace/build-debug/test/max-parallelism/job:check_parallelism_cli_over_config.d" "--remove-on-failure" "" "--required-files" "" "--datafiles" "" "--skip-return-code" "247" "/workspace/build-debug/bin/phlex" "-c" "/workspace/build-debug/test/max-parallelism/check_parallelism_cli_over_config.jsonnet" "-j" "9")
set_tests_properties([=[job:check_parallelism_cli_over_config]=] PROPERTIES  ENVIRONMENT "SPDLOG_LEVEL=debug;PHLEX_PLUGIN_PATH=/workspace/build-debug" LABELS "DEFAULT;RELEASE" SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/workspace/build-debug/test/max-parallelism/job:check_parallelism_cli_over_config.d" _BACKTRACE_TRIPLES "/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1186;add_test;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1143;_cet_add_test_detail;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;704;_cet_add_test;/workspace/test/max-parallelism/CMakeLists.txt;58;cet_test;/workspace/test/max-parallelism/CMakeLists.txt;0;")
