name: 'Handle Fix Commit'
description: 'Commits changes if possible, otherwise creates a patch and comments on the PR.'

inputs:
  tool:
    description: 'The tool name reported in commit messages and PR comments.'
    required: true
  working-directory:
    description: 'The working directory for git operations.'
    required: false
    default: 'phlex-src'
  token:
    description: 'The PAT to use for committing.'
    required: true
  pr-info-ref:
    description: 'The ref (branch name) of the PR'
    required: true
  pr-info-repo:
    description: 'The repository of the PR'
    required: true
  retry-attempts:
    description: 'The number of times to retry pushing the commit.'
    required: false
    default: '6'

runs:
  using: "composite"
  steps:
    - name: Check for changes
      id: check_changes
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: No changes to apply
      if: steps.check_changes.outputs.changes == 'false'
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: 'No automatic ${{ inputs.tool }} fixes were necessary.'

    - name: Get PR maintainer_can_modify property
      id: pr-properties
      if: steps.check_changes.outputs.changes == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          core.setOutput('maintainer_can_modify', pr.maintainer_can_modify);
    - name: Commit fixes
      if: steps.check_changes.outputs.changes == 'true' && (inputs.pr-info-repo == github.repository || steps.pr-properties.outputs.maintainer_can_modify == 'true')
      id: commit_and_push
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

        export GITHUB_TOKEN=${{ inputs.token }}
        echo "https://x-access-token:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
        trap 'rm -f ~/.git-credentials' EXIT
        git config --local credential.helper 'store --file ~/.git-credentials'

        git add -u
        git commit -m "Apply ${{ inputs.tool }} fixes"

        for i in $(seq 1 ${{ inputs.retry-attempts }}); do
          if git push origin HEAD:${{ inputs.pr-info-ref }}; then
            echo "Push successful on attempt $i."
            COMMIT_SHA=$(git rev-parse HEAD)
            echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
            echo "pushed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [ $i -eq ${{ inputs.retry-attempts }} ]; then
            break
          fi
          echo "Push failed on attempt $i. Fetching and rebasing before retry..."
          git fetch origin
          if ! git rebase origin/${{ inputs.pr-info-ref }}; then
            echo "::error::Automatic rebase failed. Please resolve conflicts manually."
            exit 1
          fi
          echo "Waiting before retry..."
          sleep $((5 * i))
        done
        echo "::error::Failed to push changes after multiple retries."
        exit 1

    - name: Notify of commit
      if: steps.commit_and_push.conclusion == 'success' && steps.commit_and_push.outputs.pushed == 'true'
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: |
          Automatic ${{ inputs.tool }} fixes pushed (commit ${{ steps.commit_and_push.outputs.commit_sha }}).
          ⚠️ **Note:** Some issues may require manual review and fixing.

    - name: Create patch
      if: steps.check_changes.outputs.changes == 'true' && inputs.pr-info-repo != github.repository && steps.pr-properties.outputs.maintainer_can_modify != 'true'
      id: create_patch
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git diff > fix.patch
        echo "patch_name=fix.patch" >> $GITHUB_OUTPUT

    - name: Upload patch
      if: steps.create_patch.outputs.patch_name
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: fix-patch
        path: ${{ inputs.working-directory }}/${{ steps.create_patch.outputs.patch_name }}

    - name: Comment with patch instructions
      if: steps.create_patch.outputs.patch_name
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: |
          Automatic fixes are available but could not be applied directly because this PR is from a fork and "Allow edits from maintainers" is not enabled.
          Please apply the patch below to fix the issues:
          1. **Download the patch file:** You can download the patch from the "Artifacts" section of this workflow run.
          2. **Apply the patch:**
             ```bash
             git apply <path/to/downloaded/fix.patch>
             ```
          3. **Commit the changes:**
             ```bash
             git commit -am "Apply ${{ inputs.tool }} fixes"
             ```
