name: 'Get PR Info'
description: 'Gets PR information for workflows triggered by an issue comment'
outputs:
  ref:
    description: 'The head ref of the PR'
    value: ${{ steps.get_pr_info.outputs.ref }}
  sha:
    description: 'The head SHA of the PR'
    value: ${{ steps.get_pr_info.outputs.sha }}
  repo:
    description: 'The full name of the head repository'
    value: ${{ steps.get_pr_info.outputs.repo }}
  base_sha:
    description: 'The SHA of the base branch'
    value: ${{ steps.get_pr_info.outputs.base_sha }}
runs:
  using: "composite"
  steps:
    - id: get_pr_info
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          core.setOutput('ref', pr.data.head.ref);
          core.setOutput('sha', pr.data.head.sha);
          core.setOutput('repo', pr.data.head.repo.full_name);
          core.setOutput('base_sha', pr.data.base.sha);
    - name: React to comment
      if: github.event_name == 'issue_comment'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      continue-on-error: true
      with:
        script: |
          github.rest.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content: 'eyes'
          });
