###INCLUDE_BEGIN### build-debug/_deps/cetmodules-src/config/package-config.cmake.preamble.in (2 passes)
########################################################################
# phlexConfig.cmake
#
#   Config for CMake project phlex 0.1.0.
#
# Generated by cetmodules 4.01.01 at Thu Feb 12 16:46:08 UTC 2026.
#
# Compiled from:
#   build-debug/_deps/cetmodules-src/config/package-config.cmake.preamble.in
#   build-debug/_deps/cetmodules-src/config/package-config.cmake.init.in
#   build-debug/genConfig/phlex-generated-config.cmake.vars.in
#   build-debug/genConfig/phlex-generated-config.cmake.deps.in
#   build-debug/genConfig/phlex-generated-config.cmake.targets.in
#   build-debug/_deps/cetmodules-src/config/package-config.cmake.bottom.in
########################################################################
###INCLUDE_END###   build-debug/_deps/cetmodules-src/config/package-config.cmake.preamble.in

###INCLUDE_BEGIN### build-debug/_deps/cetmodules-src/config/package-config.cmake.init.in (2 passes)
###############################################################################
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was phlexConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# Make find_dependency() macro available.
include(CMakeFindDependencyMacro)
###INCLUDE_END###   build-debug/_deps/cetmodules-src/config/package-config.cmake.init.in

###INCLUDE_BEGIN### build-debug/genConfig/phlex-generated-config.cmake.vars.in
####################################
# Package variable definitions.
####################################
# phlex_NAMESPACE
set(phlex_NAMESPACE "phlex")
# phlex_INCLUDE_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/include")
  file(GLOB _phlex_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/include/*")
  if (_phlex_TMP_DIR_ENTRIES)
    set_and_check(phlex_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/include")
  endif()
  unset(_phlex_TMP_DIR_ENTRIES)
endif()
# phlex_BIN_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/bin")
  file(GLOB _phlex_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/bin/*")
  if (_phlex_TMP_DIR_ENTRIES)
    set_and_check(phlex_BIN_DIR "${PACKAGE_PREFIX_DIR}/bin")
  endif()
  unset(_phlex_TMP_DIR_ENTRIES)
endif()

####################################
# Package include directories.
####################################
if (IS_DIRECTORY "${PACKAGE_PREFIX_DIR}/include")
  # CMake convention:
  set(phlex_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")
endif()
###INCLUDE_END###   build-debug/genConfig/phlex-generated-config.cmake.vars.in

###INCLUDE_BEGIN### build-debug/genConfig/phlex-generated-config.cmake.deps.in
###INCLUDE_END###   build-debug/genConfig/phlex-generated-config.cmake.deps.in

###INCLUDE_BEGIN### build-debug/genConfig/phlex-generated-config.cmake.targets.in
####################################
# Exported targets, and package components.
####################################

##################
# Automatically-generated runtime targets: phlex
##################
include("${CMAKE_CURRENT_LIST_DIR}/phlexTargets.cmake")
foreach (component IN LISTS phlex_FIND_COMPONENTS)
  include("${CMAKE_CURRENT_LIST_DIR}/phlexTargets_${component}.cmake")
endforeach()
###INCLUDE_END###   build-debug/genConfig/phlex-generated-config.cmake.targets.in

###INCLUDE_BEGIN### build-debug/_deps/cetmodules-src/config/package-config.cmake.bottom.in
# Check package components.
check_required_components(phlex)
###INCLUDE_END###   build-debug/_deps/cetmodules-src/config/package-config.cmake.bottom.in
