# CMake generated Testfile for 
# Source directory: /workspace/test/utilities
# Build directory: /workspace/build-debug/test/utilities
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[sized_tuple]=] "/workspace/build-debug/_deps/cetmodules-src/libexec/cet_exec_test" "--wd" "/workspace/build-debug/test/utilities/sized_tuple.d" "--remove-on-failure" "" "--required-files" "" "--datafiles" "" "--skip-return-code" "247" "/workspace/build-debug/bin/sized_tuple")
set_tests_properties([=[sized_tuple]=] PROPERTIES  ENVIRONMENT "SPDLOG_LEVEL=debug" LABELS "DEFAULT;RELEASE" SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/workspace/build-debug/test/utilities/sized_tuple.d" _BACKTRACE_TRIPLES "/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1186;add_test;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1143;_cet_add_test_detail;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;704;_cet_add_test;/workspace/test/utilities/CMakeLists.txt;1;cet_test;/workspace/test/utilities/CMakeLists.txt;0;")
add_test([=[sleep_for]=] "/workspace/build-debug/_deps/cetmodules-src/libexec/cet_exec_test" "--wd" "/workspace/build-debug/test/utilities/sleep_for.d" "--remove-on-failure" "" "--required-files" "" "--datafiles" "" "--skip-return-code" "247" "/workspace/build-debug/bin/sleep_for")
set_tests_properties([=[sleep_for]=] PROPERTIES  ENVIRONMENT "SPDLOG_LEVEL=debug" LABELS "DEFAULT;RELEASE" SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/workspace/build-debug/test/utilities/sleep_for.d" _BACKTRACE_TRIPLES "/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1186;add_test;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1143;_cet_add_test_detail;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;704;_cet_add_test;/workspace/test/utilities/CMakeLists.txt;3;cet_test;/workspace/test/utilities/CMakeLists.txt;0;")
add_test([=[thread_counter]=] "/workspace/build-debug/_deps/cetmodules-src/libexec/cet_exec_test" "--wd" "/workspace/build-debug/test/utilities/thread_counter.d" "--remove-on-failure" "" "--required-files" "" "--datafiles" "" "--skip-return-code" "247" "/workspace/build-debug/bin/thread_counter")
set_tests_properties([=[thread_counter]=] PROPERTIES  ENVIRONMENT "SPDLOG_LEVEL=debug" LABELS "DEFAULT;RELEASE" SKIP_RETURN_CODE "247" WORKING_DIRECTORY "/workspace/build-debug/test/utilities/thread_counter.d" _BACKTRACE_TRIPLES "/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1186;add_test;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;1143;_cet_add_test_detail;/workspace/build-debug/_deps/cetmodules-src/Modules/CetTest.cmake;704;_cet_add_test;/workspace/test/utilities/CMakeLists.txt;6;cet_test;/workspace/test/utilities/CMakeLists.txt;0;")
