# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.0)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS phlex::metaprogramming_int phlex::utilities phlex::utilities_int phlex::graph phlex::graph_int phlex::model phlex::model_int phlex::core phlex::core_int phlex::module phlex::configuration_internal phlex::configuration phlex::run_phlex)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target phlex::metaprogramming_int
add_library(phlex::metaprogramming_int INTERFACE IMPORTED)

set_target_properties(phlex::metaprogramming_int PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "Boost::boost"
)

# Create imported target phlex::utilities
add_library(phlex::utilities SHARED IMPORTED)

set_target_properties(phlex::utilities PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "spdlog::spdlog"
)

# Create imported target phlex::utilities_int
add_library(phlex::utilities_int INTERFACE IMPORTED)

set_target_properties(phlex::utilities_int PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "phlex::utilities;TBB::tbb;spdlog::spdlog"
)

# Create imported target phlex::graph
add_library(phlex::graph SHARED IMPORTED)

set_target_properties(phlex::graph PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
)

# Create imported target phlex::graph_int
add_library(phlex::graph_int INTERFACE IMPORTED)

set_target_properties(phlex::graph_int PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "phlex::graph;TBB::tbb"
)

# Create imported target phlex::model
add_library(phlex::model SHARED IMPORTED)

set_target_properties(phlex::model PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "Boost::boost;spdlog::spdlog;fmt::fmt"
)

# Create imported target phlex::model_int
add_library(phlex::model_int INTERFACE IMPORTED)

set_target_properties(phlex::model_int PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "phlex::model;spdlog::spdlog;TBB::tbb"
)

# Create imported target phlex::core
add_library(phlex::core SHARED IMPORTED)

set_target_properties(phlex::core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "TBB::tbb;phlex::metaprogramming_int;phlex::model;phlex::utilities"
)

# Create imported target phlex::core_int
add_library(phlex::core_int INTERFACE IMPORTED)

set_target_properties(phlex::core_int PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "phlex::core;phlex::metaprogramming_int;phlex::graph;phlex::model;phlex::utilities;Boost::json;TBB::tbb"
)

# Create imported target phlex::module
add_library(phlex::module INTERFACE IMPORTED)

set_target_properties(phlex::module PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "Boost::boost;Boost::json;phlex::core;phlex::configuration"
)

# Create imported target phlex::configuration_internal
add_library(phlex::configuration_internal SHARED IMPORTED)

set_target_properties(phlex::configuration_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
)

# Create imported target phlex::configuration
add_library(phlex::configuration INTERFACE IMPORTED)

set_target_properties(phlex::configuration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "Boost::json;phlex::core;phlex::configuration_internal"
)

# Create imported target phlex::run_phlex
add_library(phlex::run_phlex SHARED IMPORTED)

set_target_properties(phlex::run_phlex PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/workspace/build-tsan;/workspace"
  INTERFACE_LINK_LIBRARIES "phlex::core;Boost::json;Boost::boost"
)

# Import target "phlex::utilities" for configuration "RelWithDebInfo"
set_property(TARGET phlex::utilities APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(phlex::utilities PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/workspace/build-tsan/libphlex_utilities.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libphlex_utilities.so"
  )

# Import target "phlex::graph" for configuration "RelWithDebInfo"
set_property(TARGET phlex::graph APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(phlex::graph PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "TBB::tbb;phlex::utilities"
  IMPORTED_LOCATION_RELWITHDEBINFO "/workspace/build-tsan/libphlex_graph.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libphlex_graph.so"
  )

# Import target "phlex::model" for configuration "RelWithDebInfo"
set_property(TARGET phlex::model APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(phlex::model PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "phlex::graph;phlex::utilities;TBB::tbb"
  IMPORTED_LOCATION_RELWITHDEBINFO "/workspace/build-tsan/libphlex_model.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libphlex_model.so"
  )

# Import target "phlex::core" for configuration "RelWithDebInfo"
set_property(TARGET phlex::core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(phlex::core PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "phlex::graph;Boost::json;spdlog::spdlog"
  IMPORTED_LOCATION_RELWITHDEBINFO "/workspace/build-tsan/libphlex_core.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libphlex_core.so"
  )

# Import target "phlex::configuration_internal" for configuration "RelWithDebInfo"
set_property(TARGET phlex::configuration_internal APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(phlex::configuration_internal PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "Boost::json;phlex::core"
  IMPORTED_LOCATION_RELWITHDEBINFO "/workspace/build-tsan/libphlex_configuration_internal.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libphlex_configuration_internal.so"
  )

# Import target "phlex::run_phlex" for configuration "RelWithDebInfo"
set_property(TARGET phlex::run_phlex APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(phlex::run_phlex PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/workspace/build-tsan/librun_phlex.so"
  IMPORTED_SONAME_RELWITHDEBINFO "librun_phlex.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
